spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.159.131:3306/gulimall_pms
  cloud:
    nacos:
      discovery: ## 注册中心地址
        server-addr: 192.168.166.1:8848
  application:
    name: gulimall-product
  jackson: #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 # 设置时区
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 设置id自增
      logic-delete-value: 1 # 1为已经删除
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level: # 设置日志打印级别
    com.dhx.gulimall: debug
