spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.159.131:3306/gulimall_ums
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.166.1:8848
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates: # 断言规则
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates: # 断言规则
            - Query=url,qq
  application:
    name: gulimall-gateway
  main:
    web-application-type: reactive # springmvc 与 gateway不兼容
server:
  port: 88

